--- makefile_4430	2005-05-19 07:45:45.000000000 -0400
+++ ../makefile	2006-11-29 20:05:44.000000000 -0500
@@ -21,7 +21,9 @@
 	cd FFNet; make
 	cd artsynth; make
 	cd main; make main_Praat.o $(ICON)
+	cd jscript; make
 	$(CC) -o praat main/main_Praat.o $(MAIN_ICON) fon/libfon.a \
 		LPC/libLPC.a FFNet/libFFNet.a dwtools/libdwtools.a \
 		artsynth/libartsynth.a fon/libfon.a dwsys/libdwsys.a \
+		jscript/mono_embed.o jscript/mono_embed_host.o jscript/mono_embed_libs.o `pkg-config --libs mono` -lz \
 		sys/libsys.a GSL/libgsl.a ipa/libipa.a $(LIBS)
