--- originals-4514/makefile	2007-02-20 07:14:50.000000000 -0500
+++ ../makefile	2007-02-20 07:09:40.000000000 -0500
@@ -20,8 +20,10 @@
 	cd LPC; make
 	cd FFNet; make
 	cd artsynth; make
+	cd scripting; make
 	cd main; make main_Praat.o $(ICON)
 	$(CC) -o praat main/main_Praat.o $(MAIN_ICON) fon/libfon.a \
 		LPC/libLPC.a FFNet/libFFNet.a dwtools/libdwtools.a \
 		artsynth/libartsynth.a fon/libfon.a dwsys/libdwsys.a \
+		scripting/mono_embed.o scripting/mono_embed_host.o scripting/mono_embed_libs.o `pkg-config --libs mono` -lz \
 		sys/libsys.a GSL/libgsl.a kar/libkar.a $(LIBS)
